config/routes.rb
Rails.application.routes.draw do

  get "upload" => "images#new", :as => "upload"

  get 'images/new'
  get 'images/create'
  get 'images/destroy'
  get 'images/index'
  get 'categories/nea'
  get 'categories/creat'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/destroy'
  get 'categories/show'

  resources :images, :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'images#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :images

end

app/models/image.rb
class Image < ActiveRecord::Base
    belongs_to :category

    mount_uploader :image, ImageUploader

    before_save :update_image_attributes

    private
       def update_image_attributes
        if image.present? && image_changed?
            self.image_content_type = image.file.content_type
            self.image_file_size = image.file.size
        end    
       end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :getCategoryNav

    protect_from_forgery with: :exception

    private
    def getCategoryNav
        @categoryNav = Category.all
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category Created"

      redirect_to root_path
    else
      render 'new'
    end  
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = "Category Updated"

      redirect_to category_path(params[:id])
    else
      render 'edit' 
    end  
  end

  def destroy
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      flash[:notice] = "Image Created"

      redirect_to root_path
    else
      render 'new'
    end  
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    flash[:notice] = "Image Removed"
    redirect_to images_path
  end

  def index
    @images = Image.all
    @categories = Category.all
  end

  private
    def image_params
      params.require(:image).permit(:image, :category_id, :image_title, :image_description, :image_file_size, :image_content_type, :remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>
<!-- chek for errors -->
   <% if @category.errors.any? %>
      <% @category.errors.full_messages.each do |msg| %>
         <!-- show errors -->
          <div class="alert alert-danger"><%= msg %></div>
           <% end %>
          <% end %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name ,class:'form-control'%>
          </div>
          <br>
           <%= f.submit "submit", class:'btn btn-primary' %>
           <%= link_to "Cancel", categories_path, class: 'btn btn-default' %>
         <% end %>

         <h3 class="page-header">Images in <%=@category.name %></h3>
         <div id="edit_images">
            <% if @images.exists? %>
              <% @images.each_slice(6) do |image| %>
                <div class="row">
                  <% image.each do |image|%>
                    <div class="scol-md-2">
                       <%= image_tag image.image_url(:thumb) %>
                       <center><%= link_to "Delete", image_path(image), class:'delete', method: :delete, data: {confirm:'Are you sure?'} %></center>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
         </div>

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %>
<!-- chek for errors -->
   <% if @category.errors.any? %>
      <% @category.errors.full_messages.each do |msg| %>
         <!-- show errors -->
          <div class="alert alert-danger"><%= msg %></div>
           <% end %>
          <% end %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name ,class:'form-control'%>
          </div>
          <br>
           <%= f.submit "submit", class:'btn btn-primary' %>
           <%= link_to "Cancel", categories_path, class: 'btn btn-default' %>
         <% end %>

app/views/categories/show.html.erb
 <div id="gallery">
    <h2><%= @category.name %> <small class="pull-right"><%= link_to "Edit", edit_category_path %></small></h2>
  <% if @images.exists? %>
    <% @images.each_slice(4) do |image|%>
      <div class="row">
        <% image.each do |image|%>
          <div class="col-md-3">
            <div class="photo photo-type-line">
              <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                <div class="photo-info">
                  <div class="headline"><%= image.image_title %></div>
                  <div class="line"></div>
                  <div class="desc"><%= image.image_description %></div>
                </div>
                <div class="mask"></div> 
              </a>
              <div class="photo-img"><%= image_tag image.image_url(:thumb) %></div>
            </div>
          </div>
             <% end %>
           </div>
        <% end %>
        <% else %>
        <p>There are no images</p>
    <% end %>
    </div>

app/views/images/index.html.erb
 <div id="gallery">
    <h2>All Images</h2>
  <% if @images.exists? %>
    <% @images.each_slice(4) do |image|%>
      <div class="row">
        <% image.each do |image|%>
          <div class="col-md-3">
            <div class="photo photo-type-line">
              <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                <div class="photo-info">
                  <div class="headline"><%= image.image_title %></div>
                  <div class="line"></div>
                  <div class="desc"><%= image.image_description %></div>
                </div>
                <div class="mask"></div> 
              </a>
              <div class="photo-img"><%= image_tag image.image_url(:thumb) %></div>
            </div>
          </div>
             <% end %>
           </div>
        <% end %>
        <% else %>
        <p>There are no images</p>
    <% end %>
    </div>

app/views/images/new.html.erb
<h2>Upload Image</h2>
<%= form_for @image, :html => {:multipart => true} do |f| %>
  <!-- check for errors -->
  <% if @image.errors.any? %>
    <% @image.errors.full_messages.each do |msg| %>
      
      <div class="alert alert-danger"><% msg %></div>
    <% end %>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image_title %>
    <%= f.text_field :image_title ,class:'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control'%>
  </div>

  <div class="form-group">
     <%= f.label :image_description %>
     <%= f.text_area :image_description ,class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image%>
  </div>

  <br>

    <%= f.submit "Submit", class:'btn btn-primary'%>
    <%=link_to "Cancel", images_path, class:'btn btn-default'%>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RGallery</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
   
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">RailsCMS</a>    
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path %></li>
                <% @categoryNav.each do |category| %>
                    <li><%= link_to category.name, category_path(category.id) %></li>
                <% end %>
              </ul>
              <ul class="nav navbar-nav pull-right">
                <li><%= link_to "Upload Photo", upload_path %></li>
                <li><%= link_to "Add Category", new_category_path %></li>
              </ul>
            </div><!--/.nav-collapse-->
        </div>
    </nav>
  <section>
      <div class="container">
        <!--Alert & Messages-->
        <% if flash[:notice] %>
          <div class="alert alert-success"><%= flash[:notice] %></div>
        <% end %>

        <% if flash[:alert] %>
         <div class="alert alert-danger"><%= flash[:alert] %> </div>
        <% end %> 
       <%= yield %>
      </div><!--/.container-->
  </section>

  <footer>
    <p>Copyright @copy; 2019, rGallery</p>
  </footer>
    
  </body>
</html>